### ISSUE TITLE
Reimagine Ionic（App 中的 App）

### ISSUE THREAD

**Issue by aprilorange** [LightBulb/LightBulb#13]
类似 Ionic / PhoneGap 之类的理念，不过不是让你单独打包成一个新的 App，而是建立一个这类应用的市场，你可以直接在这个市场中安装 App，作为一个“应用中的应用”。并不需要打包，开发者做的只是编写 HTML 调用 API 这种事。你是用 HTML 技术构建了一个应用，然后在市场注册，用户就可以搜索安装。当然，这些应用只能在这个市场中运行。

**高能** 请注意，这并不是像 “云集” 这个 APP 做的那样，虽然理念类似，但云集完全只是“网页快捷方式”的集合，而我描述的是更接近 Ionic 的这种应用，可以让这些 HTML 应用调用 API。

*抱歉我的语文是自学的*

**Comment by 7bitex** [comment]
在作为一个 HTML app 市场的同时，为 app 提供运行环境（是这个意思吧）。

**Comment by aprilorange** [comment]
@7bitex 大概是。让这个市场暴露一些接口给这些 HTML 应用让它表现得更原生。类似 Chrome 和 Chrome 插件的关系。

**Comment by 7bitex** [comment]
@aprilorange 虽然很有意思，然而这个市场和使用 Ionic / PhoneGap 打包应用并发布到平台原生的市场，除了能缩小单个 app 的体积之外好像并没有明显的优势。

而且，多应用协作的需求可以实现吗？

**Comment by aprilorange** [comment]
@7bitex 把开发难度降低这一点就有很大价值，而且不用管打包到各平台的事了。还没有额外的下载安装。

多应用协作是什么？如果是指同时运行多个应用那应该不是问题，应该它们并不是真正的应用，只要有个入口文件之类的概念就行。

**Comment by 7bitex** [comment]
@aprilorange “多应用协作”指的是，可以使用系统原生的应用切换功能，在这个市场正在运行的 apps 之间切换。比如 iOS 的双击 Home 键，Android 的最近应用列表，这样。

Google 了一圈发现 Android 可以实现同一个 app 在最近应用列表里出现多个 tasks。iOS 不太熟悉，不知道能不能实现这样的效果。

**Comment by aprilorange** [comment]
同不知道 iOS，Android 上的 Chrome 就可以把每个标签页作为独立的应用出现在最近应用列表。 
------------------ Original ------------------

**Comment by aprilorange** [comment]
重蹈历史的覆辙 💔

**Comment by 7bitex** [comment]
@aprilorange 为什么？

**Comment by vanishs** [comment]
这个是免安装版app store!

**Comment by aprilorange** [comment]
@7bitex http://v2ex.com/t/211157?p=1#r_2301546 感觉很像 ChromeOS

**Comment by vanishs** [comment]
1:这个软件有人群多的优势吗？
2:如果有，那么那么多个app在里面怎么公平的展现个用户呢？app们会愿意吗？
3:你有想过如果你做为个人开发，这个app平台对你有什么一定要放在这里的理由吗？

**Comment by aprilorange** [comment]
@vanishs 如果这个应用本身就可以作为一个桌面 APP 的话就更有 ChromeOS 的样子了，然并卵。。

**Comment by aprilorange** [comment]
@vanishs 降低到这种开发难度的话市场应该是有的，谁能告诉我为什么 ChromeOS 失败了。。估计还是没市场 233

**Comment by 7bitex** [comment]
@aprilorange 我倒是觉得 Chrome OS 没有失败啊，只是时机还不成熟，从基于本地的传统操作系统直接跳到基于云端的系统，动作太大闪了腰吧……

**Comment by aprilorange** [comment]
@7bitex 感觉这个 idea 是需要拥有生态圈的公司才能解决的……比如 Apple、 M$、Google 233

我还想加一个…… 小米 😂

**Comment by 7bitex** [comment]
@aprilorange 小米去死啦！
