### ISSUE TITLE
微博私信独立客户端

### ISSUE THREAD

**Issue by aprilorange** [LightBulb/LightBulb#22]
居然有 Twitter 私信独立客户端 https://itunes.apple.com/app/id1016344415

那么微博有吗？

**Comment by aprilorange** [comment]
以前看到过微博的 API 似乎不能私信 💩

**Comment by 7beta** [comment]
私信拿出来单独做一个客户端的话，就有点 IM 的意思了，我想对 API 的访问次数应该会有不小的要求吧。微博（接触腾讯比较多，新浪不太熟悉）的私信客户端好像需要申请才可以用，然而请求次数也是有限的，就算通过审核、企业合作，作为 IM 也不是很足够用。

如果能把 SNS 和 IM 结合起来好像挺有意思，比如 Twitter + Telegram。有这样一个平台就好了。
