### ISSUE TITLE
一起读源码

### ISSUE THREAD

**Issue by xh4n3** [LightBulb/LightBulb#32]
针对大项目
其实源码如果可以在线跟很多人一起读 多好。
就是每个人都可以加注释。
注释可以是 markdown 格式的。
跟 wikipedia 一样的模式
或者 比较习惯于 IDE 的话，还是做一下 Git 方面的改造，不允许修改已有代码，只允许添加新注释。

**Comment by egoist** [comment]
类似的想法 http://insekai.com/timeline/3772
