### ISSUE TITLE
加密的百度云 app

### ISSUE THREAD

**Issue by xh4n3** [LightBulb/LightBulb#35]
用 objc 或者 react native 开发一个 ios app，解决用户隐私问题
让用户自己生成公私钥，放进 app 里面，app 调用 百度云 api，可以将本地照片加密后上传到云空间。

疑问：
开源？
能不能对照片进行加密操作？
百度云 api 让不让这么调用？
法律风险？

**Comment by egoist** [comment]
我觉得是可以实现的，但是用户不会太多，基本只有 geeker 同学用 😐

**Comment by xh4n3** [comment]
可能吧 
我给长辈智能手机的照片备份解决方案就是百度云
但推荐的时候其实很矛盾 要是帐号被盗 照片全泄露了
不知道谷歌入华会不会把好用的google photos带进来 如果进来百度云都得死。。
