### ISSUE TITLE
CLI + Electron to browse image on disk

### ISSUE THREAD

**Issue by egoist** [LightBulb/LightBulb#59]
Say there is a folder which contains a few images:

![http://ooo.0o0.ooo/2016/02/03/56b210ea48732.png](http://ooo.0o0.ooo/2016/02/03/56b210ea48732.png)

I want to make it available to run the command `view .` in this directory so that it opens a window which is brought by Electron. And I simply press ⬅️➡️ to navigate.

**Comment by 2yuri** [comment]
https://github.com/2yuri/viewtronic-cli

菊苣，我今天写了一个工具，见上。

**Comment by 2yuri** [comment]
![GIF](https://camo.githubusercontent.com/d5ab2d31373d8c202f3a318a22f5971563a80837/687474703a2f2f37786e7178622e636f6d312e7a302e676c622e636c6f7564646e2e636f6d2f342545362539432538382d31392d3230313625323031392d30322d30382e676966)

**Comment by egoist** [comment]
How about using [electron-prebuilt](https://github.com/mafintosh/electron-prebuilt) directly to open the app?

**Comment by 2yuri** [comment]
yep! 就是用的 electron 打开的，electron-prebuilt download 太慢，我自己重新把app和electron打了个包。

**Comment by egoist** [comment]
可以指定用 npm.taobao.org 的镜像下载，还有 app 怎么不开源 😂

**Comment by 2yuri** [comment]
等明天的，晚上没带电脑回来。😂

**Comment by xream** [comment]
我直接 `open -a preview .`

**Comment by egoist** [comment]
@xream 厉害了，忘了还可以这样 👍🏻 😂
