### ISSUE TITLE
时光轴

### ISSUE THREAD

**Issue by noctiomg** [LightBulb/LightBulb#78]
一个开放接口的时光轴，可以在时光轴官网记录东西，也可以通过接口记录东西，开放给各个博客，可以自定义主题……
这东西有卵用么……
说起来真的没人做过这个么……

**Comment by egoist** [comment]
不是 微博/twitter API 吗 ๛ก(ｰ̀ωｰ́ก)

**Comment by noctiomg** [comment]
说起来好像是这样。。。貌似可以关了诶2333

**Comment by beta** [comment]
「博客」、「自定义主题」，更像是 Tumblr（。
