### ISSUE TITLE
基于 Electron 的视频播放器

### ISSUE THREAD

**Issue by egoist** [LightBulb/LightBulb#97]
QuickTime Player 支持的格式太少，而 IINA 还行，就是不知道怎么开新窗口 😅

用 Electron / HTML5 video 做个视频播放器应该没什么问题，而且似乎可以做更多有趣的事 (always bet on web technology)

> note: [why Electron?](https://www.producthunt.com/posts/caprine-2#comment-468390)

**Comment by xream** [comment]
通用多开教程:

![image](https://cloud.githubusercontent.com/assets/1210282/26229674/1cacb1f8-3c76-11e7-972e-1e9099f4e7cd.png)

**Comment by djyde** [comment]
WebTorrent?

**Comment by egoist** [comment]
突然意识到 HTML5 `<video>` 只支持三种格式 😂 https://github.com/egoist/anii
